<a href="https://colab.research.google.com/github/mathewalex262006/ict/blob/main/internship4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
text = """Transforming through innovation ICTAK Offline Programs:
 Back to physical sessions. Join our Offline Programs in Kerala’s IT parks
  for face-to-face sessions led by industry experts, offering certifications in Data Science,
   Cybersecurity, and Software Testing, with scholarships available, spanning ~3 months
   including internship. The ICT Academy of Kerala publishes an annual international ​journal, ‘Convergence’.
   It is a multidisciplinary journal which ​aims to provide trailblazing ideas on engineering, ​technology,
   and employability where academicians, research ​scholars, and industry professionals can bestow upon their
   ​ingenious and prolific ideas in the form of articles, empirical ​studies, case studies, and book reviews."""

In [15]:
len(text)

750

In [16]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [17]:
punct_removed =''
for char in text:
  if char not in string.punctuation:
     punct_removed += char
punct_removed

'Transforming through innovation ICTAK Offline Programs\n Back to physical sessions Join our Offline Programs in Kerala’s IT parks\n  for facetoface sessions led by industry experts offering certifications in Data Science\n   Cybersecurity and Software Testing with scholarships available spanning 3 months\n   including internship The ICT Academy of Kerala publishes an annual international \u200bjournal ‘Convergence’\n   It is a multidisciplinary journal which \u200baims to provide trailblazing ideas on engineering \u200btechnology\n   and employability where academicians research \u200bscholars and industry professionals can bestow upon their\n   \u200bingenious and prolific ideas in the form of articles empirical \u200bstudies case studies and book reviews'

In [18]:
len(punct_removed)

729

In [19]:
import re
cleaned_text = re.sub(r'[^a-zA-Z0-9 ]','',punct_removed)
cleaned_text = re.sub(r'\s+',' ',cleaned_text).strip()
cleande_text = cleaned_text.lower()
cleaned_text

'Transforming through innovation ICTAK Offline Programs Back to physical sessions Join our Offline Programs in Keralas IT parks for facetoface sessions led by industry experts offering certifications in Data Science Cybersecurity and Software Testing with scholarships available spanning 3 months including internship The ICT Academy of Kerala publishes an annual international journal Convergence It is a multidisciplinary journal which aims to provide trailblazing ideas on engineering technology and employability where academicians research scholars and industry professionals can bestow upon their ingenious and prolific ideas in the form of articles empirical studies case studies and book reviews'

In [20]:
len(cleaned_text)

702

In [21]:
import nltk

In [22]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [23]:
from nltk.tokenize import word_tokenize

In [24]:
word = nltk.word_tokenize(cleaned_text)
word

['Transforming',
 'through',
 'innovation',
 'ICTAK',
 'Offline',
 'Programs',
 'Back',
 'to',
 'physical',
 'sessions',
 'Join',
 'our',
 'Offline',
 'Programs',
 'in',
 'Keralas',
 'IT',
 'parks',
 'for',
 'facetoface',
 'sessions',
 'led',
 'by',
 'industry',
 'experts',
 'offering',
 'certifications',
 'in',
 'Data',
 'Science',
 'Cybersecurity',
 'and',
 'Software',
 'Testing',
 'with',
 'scholarships',
 'available',
 'spanning',
 '3',
 'months',
 'including',
 'internship',
 'The',
 'ICT',
 'Academy',
 'of',
 'Kerala',
 'publishes',
 'an',
 'annual',
 'international',
 'journal',
 'Convergence',
 'It',
 'is',
 'a',
 'multidisciplinary',
 'journal',
 'which',
 'aims',
 'to',
 'provide',
 'trailblazing',
 'ideas',
 'on',
 'engineering',
 'technology',
 'and',
 'employability',
 'where',
 'academicians',
 'research',
 'scholars',
 'and',
 'industry',
 'professionals',
 'can',
 'bestow',
 'upon',
 'their',
 'ingenious',
 'and',
 'prolific',
 'ideas',
 'in',
 'the',
 'form',
 'of',
 'articles',
 'empirical',
 'studies',
 'case',
 'studies',
 'and',
 'book',
 'reviews']

In [25]:
len(word)

96

In [26]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [27]:
stop_words = stopwords.words('english')
stop_words

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [28]:
filtered_tokens = [words for words in word if words not in stop_words]
filtered_tokens

['Transforming',
 'innovation',
 'ICTAK',
 'Offline',
 'Programs',
 'Back',
 'physical',
 'sessions',
 'Join',
 'Offline',
 'Programs',
 'Keralas',
 'IT',
 'parks',
 'facetoface',
 'sessions',
 'led',
 'industry',
 'experts',
 'offering',
 'certifications',
 'Data',
 'Science',
 'Cybersecurity',
 'Software',
 'Testing',
 'scholarships',
 'available',
 'spanning',
 '3',
 'months',
 'including',
 'internship',
 'The',
 'ICT',
 'Academy',
 'Kerala',
 'publishes',
 'annual',
 'international',
 'journal',
 'Convergence',
 'It',
 'multidisciplinary',
 'journal',
 'aims',
 'provide',
 'trailblazing',
 'ideas',
 'engineering',
 'technology',
 'employability',
 'academicians',
 'research',
 'scholars',
 'industry',
 'professionals',
 'bestow',
 'upon',
 'ingenious',
 'prolific',
 'ideas',
 'form',
 'articles',
 'empirical',
 'studies',
 'case',
 'studies',
 'book',
 'reviews']

In [29]:
len(filtered_tokens)

70

In [30]:
from nltk.stem import PorterStemmer,WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [31]:
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

In [32]:
stemmed_words = [stemmer.stem(word) for word in filtered_tokens]
stemmed_words

['transform',
 'innov',
 'ictak',
 'offlin',
 'program',
 'back',
 'physic',
 'session',
 'join',
 'offlin',
 'program',
 'kerala',
 'it',
 'park',
 'facetofac',
 'session',
 'led',
 'industri',
 'expert',
 'offer',
 'certif',
 'data',
 'scienc',
 'cybersecur',
 'softwar',
 'test',
 'scholarship',
 'avail',
 'span',
 '3',
 'month',
 'includ',
 'internship',
 'the',
 'ict',
 'academi',
 'kerala',
 'publish',
 'annual',
 'intern',
 'journal',
 'converg',
 'it',
 'multidisciplinari',
 'journal',
 'aim',
 'provid',
 'trailblaz',
 'idea',
 'engin',
 'technolog',
 'employ',
 'academician',
 'research',
 'scholar',
 'industri',
 'profession',
 'bestow',
 'upon',
 'ingeni',
 'prolif',
 'idea',
 'form',
 'articl',
 'empir',
 'studi',
 'case',
 'studi',
 'book',
 'review']

In [33]:
lemma_words = [lemmatizer.lemmatize(word) for word in filtered_tokens]
lemma_words

['Transforming',
 'innovation',
 'ICTAK',
 'Offline',
 'Programs',
 'Back',
 'physical',
 'session',
 'Join',
 'Offline',
 'Programs',
 'Keralas',
 'IT',
 'park',
 'facetoface',
 'session',
 'led',
 'industry',
 'expert',
 'offering',
 'certification',
 'Data',
 'Science',
 'Cybersecurity',
 'Software',
 'Testing',
 'scholarship',
 'available',
 'spanning',
 '3',
 'month',
 'including',
 'internship',
 'The',
 'ICT',
 'Academy',
 'Kerala',
 'publishes',
 'annual',
 'international',
 'journal',
 'Convergence',
 'It',
 'multidisciplinary',
 'journal',
 'aim',
 'provide',
 'trailblazing',
 'idea',
 'engineering',
 'technology',
 'employability',
 'academician',
 'research',
 'scholar',
 'industry',
 'professional',
 'bestow',
 'upon',
 'ingenious',
 'prolific',
 'idea',
 'form',
 'article',
 'empirical',
 'study',
 'case',
 'study',
 'book',
 'review']

In [34]:
cleaned_text = ' '.join(lemma_words)
cleaned_text

'Transforming innovation ICTAK Offline Programs Back physical session Join Offline Programs Keralas IT park facetoface session led industry expert offering certification Data Science Cybersecurity Software Testing scholarship available spanning 3 month including internship The ICT Academy Kerala publishes annual international journal Convergence It multidisciplinary journal aim provide trailblazing idea engineering technology employability academician research scholar industry professional bestow upon ingenious prolific idea form article empirical study case study book review'

In [35]:
import pandas as pd
data = pd.read_csv("/content/spam - spam.csv")
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [36]:
data = data[['v1','v2']]
data.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [37]:
data.shape

(5572, 2)

In [38]:
data['v1'].value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [39]:
punct_free_text=""
def remove_punctuation(text):
  punct_free_text = "".join([i for i in text if i not in string.punctuation])
  punct_free_text = punct_free_text.lower()
  return punct_free_text

data['punct_free_text'] = data['v2'].apply(lambda x:remove_punctuation(x))
data.head()

,v1,v2,punct_free_text
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i dont think he goes to usf he lives aroun...

In [42]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
  tokens = word_tokenize(text)
  tokens = [word for word in tokens if word not in stopwords.words('english')]
  tokens = [lemmatizer.lemmatize(word) for word in tokens]
  return ' '.join(tokens)

data ['final_cleaned_message'] = data['punct_free_text'].apply(preprocess_text)
data.head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,v1,v2,punct_free_text,final_cleaned_message
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i dont think he goes to usf he lives aroun...,nah dont think go usf life around though

In [43]:
from sklearn.feature_extraction.text import CountVectorizer

cnt_vector = CountVectorizer()
X = cnt_vector.fit_transform(data['final_cleaned_message'])
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 47064 stored elements and shape (5572, 8803)>

In [46]:
y = data['v1'].map({'ham':0,'spam':1})
X.shape,y.shape

((5572, 8803), (5572,))

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [48]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((4457, 8803), (1115, 8803), (4457,), (1115,))

In [49]:
nb_model = MultinomialNB()
nb_model.fit(x_train,y_train)
y_pred = nb_model.predict(x_test)

In [50]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9748878923766816
[[949  16]
 [ 12 138]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       965
           1       0.90      0.92      0.91       150

    accuracy                           0.97      1115
   macro avg       0.94      0.95      0.95      1115
weighted avg       0.98      0.97      0.98      1115

In [56]:
test_msg = "Enter the 6-digit code below to verify your identity and regain access to your LinkedIn account.82474Thanks for helping us keep your account secure.The LinkedIn TeamWhen and where this happened:Date: May 8, 2026 at 5:02 AM GMTOperating System: WindowsBrowser: ChromeApproximate Location: Thiruvananthapuram, Kerala, IndiaNever miss an update with the LinkedIn appDownload on the App Store Get it on Google PlayThis email was intended for mathewalex2.6.2006@gmail.coLearn why we included this.You are receiving LinkedIn notification emails.HelpLinkedIn2026 LinkedIn Corporation, 1‌000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of Linked"
test_msg = remove_punctuation(test_msg)
test_msg = preprocess_text(test_msg)
test_vector = cnt_vector.transform([test_msg])
prediction = nb_model.predict(test_vector)
if prediction[0] == 0:
  print("Ham")
else:
  print("Spam")

Spam